### ISSUE TITLE
Some CRAN and BioC packages not found for the graph

### ISSUE THREAD

**Issue by stanstrup** [sneumann/metaRbolomics#1]
There appears to be some misspells:

```r
reviewTables %>% 
    filter(!(Package %in% devtools:::packages()[,"Package"])) %>% 
    filter(grepl("CRAN|BioC", Repo)) %>% 
    as_tibble
```

| Package                          | Repo        |
|----------------------------------|-------------|
| XCMS                             | BioC        |
| IsoCorrectoR and IsoCorrectoRGUI | BioC        |
| Miso                             | CRAN        |
| MSeasy                           | CRAN        |
| OSD                              | CRAN        |
| CliqueMS                         | CRAN,GitHub |
| RAMClustR                        | CRAN,GitHub |
| LipidMS                          | CRAN        |
| CluMSID                          | BioC        |
| ASICSdata                        | BioC        |
| mQTL-NMR                         | BioC        |
| STATegRa STATegra EMS            | BioC        |
| Metabomxtr                       | BioC        |
| metabolomics                     | CRAN        |
| MOFA                             | BioC        |
| CluMSID                          | BioC        |
| pwomics                          | BioC        |
| PaPi                             | BioC        |
| pathwayPCA                       | BioC        |
| faahKO                           | BioC        |
| mtbls2                           | BioC        |
| msdata                           | BioC        |
| RMassBankData                    | BioC        |
| plasFIA                          | BioC        |
| ASICSdata                        | BioC        |

XCMS should be lowercase. All of them can't be capitalization issues I imagine. How do you wan't to handle? I try to trace it down? I fix just the CSV or the paper (started lowercasing xcms in the paper)?

**Comment by stanstrup** [comment]
Many are capitalization issues. Some have been removed from CRAN.

**Comment by stanstrup** [comment]
Some don't seem to have a good reason to not show up e.g. pathwayPCA. It looks like it doesn't include data packages like faahKO and RMassBankData and also doesn't track packages only in the devel branch e.g. CluMSID.

**Comment by stanstrup** [comment]
Packages where capitalization is the problem:

```r
all_packs <- devtools:::packages()[,"Package"]

reviewTables %>% 
    filter(!(Package %in% all_packs)) %>% 
    filter(grepl("CRAN|BioC", Repo)) %>% 
    as_tibble %>% 
    mutate(lowercasename = tolower(Package)) %>% 
    filter(lowercasename %in% tolower(all_packs)) %>% 
    left_join(tibble(real_name = all_packs, lowercasename =tolower(all_packs)), by = "lowercasename") %>% 
    select(Package, Repo, lowercasename, real_name)
```

![image](https://user-images.githubusercontent.com/4532682/62648943-16a7d500-b954-11e9-87ae-d7b1ce6c3290.png)

**Comment by stanstrup** [comment]
Here are the issues:

| Package                          | Repo        | Problem                                                                     |
|----------------------------------|-------------|-----------------------------------------------------------------------------|
| XCMS                             | BioC        | capitalization                                                              |
| IsoCorrectoR and IsoCorrectoRGUI | BioC        | Two names                                                                   |
| Miso                             | CRAN        | Archived on 2019-06-02 as requires non-portable package.                    |
| MSeasy                           | CRAN        | Archived on 2019-06-02 as requires non-portable package.                    |
| OSD                              | CRAN        | capitalization                                                              |
| CliqueMS                         | CRAN,GitHub | Archived on 2019-06-02 as requires non-portable package.                    |
| RAMClustR                        | CRAN,GitHub | Archived on 2019-06-02 as requires non-portable package.                    |
| LipidMS                          | CRAN        | Archived on 2019-06-02 as requires non-portable package.                    |
| CluMSID                          | BioC        | In devel only                                                               |
| ASICSdata                        | BioC        | data pack?                                                                  |
| mQTL-NMR                         | BioC        | - to . But asl not in current                                               |
| STATegRa STATegra EMS            | BioC        | Two names                                                                   |
| Metabomxtr                       | BioC        | capitalization                                                              |
| metabolomics                     | CRAN        | Archived on 2019-02-28 as check issues were not corrected despite reminder. |
| MOFA                             | BioC        | In devel only                                                               |
| CluMSID                          | BioC        | In devel only                                                               |
| pwomics                          | BioC        | capitalization                                                              |
| PaPi                             | BioC        | capitalization                                                              |
| pathwayPCA                       | BioC        | no "DependsOnMe"                                                            |
| faahKO                           | BioC        | data pack?                                                                  |
| mtbls2                           | BioC        | data pack?                                                                  |
| msdata                           | BioC        | data pack?                                                                  |
| RMassBankData                    | BioC        | data pack?                                                                  |
| plasFIA                          | BioC        | Experimental package?                                                       |
| ASICSdata                        | BioC        | data pack?                                                                  |

**Comment by sneumann** [comment]
Great work and list. Indeed, many are data packs. Half of the "two names" are go back to me in the manuscript. Removed the second one in the CSV now. The "Removed from CRAN" are probably 
because they depended on mzR which didn't compile there earlier this year. So, I fixed all that are fixable 
in the CSV and currently recreating the figure. The rest are `wontfix` for now. Yours, Steffen
